name: Build

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]


jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    continue-on-error: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install General Dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get -y install --no-install-recommends python3-dev

      - name: Install Python Dependencies
        shell: bash
        run: |
          python -m pip install wheel
          python -m pip install pylint yapf

      - name: Run YAPF
        shell: bash
        run: |
          python -m yapf --verbose --diff --recursive src

      - name: Run Pylint
        shell: bash
        run: |
          python -m pylint src
