name: Build (develop)

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]


jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    continue-on-error: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false

      - name: Install General Dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get -y install --no-install-recommends python3-dev

      - name: Install Python Dependencies
        shell: bash
        run: |
          pip3 install wheel
          pip3 install pylint yapf

      - name: Run YAPF
        shell: bash
        run: |
          yapf --verbose --diff --recursive src

      - name: Run Pylint
        shell: bash
        run: |
          pylint src
